/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar clientes */
        get: operations["listCustomers"];
        put?: never;
        /** Criar cliente */
        post: operations["createCustomer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter cliente */
        get: operations["getCustomer"];
        /** Atualizar cliente (completo) */
        put: operations["replaceCustomer"];
        post?: never;
        /** Remover cliente */
        delete: operations["deleteCustomer"];
        options?: never;
        head?: never;
        /** Atualizar cliente (parcial) */
        patch: operations["updateCustomer"];
        trace?: never;
    };
    "/charges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar cobranças */
        get: operations["listCharges"];
        put?: never;
        /** Criar cobrança (cartão/boleto/pix/parcelado) */
        post: operations["createCharge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/charges/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter cobrança */
        get: operations["getCharge"];
        put?: never;
        post?: never;
        /** Cancelar cobrança (DELETE como alias) */
        delete: operations["cancelCharge"];
        options?: never;
        head?: never;
        /** Atualizar cobrança (metadata/descrição) */
        patch: operations["updateCharge"];
        trace?: never;
    };
    "/charges/{id}/capture": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Capturar cobrança (quando captura manual) */
        post: operations["captureCharge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/charges/{id}/refunds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Criar reembolso total/parcial */
        post: operations["refundCharge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar assinaturas */
        get: operations["listSubscriptions"];
        put?: never;
        /** Criar assinatura */
        post: operations["createSubscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscriptions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter assinatura */
        get: operations["getSubscription"];
        put?: never;
        post?: never;
        /** Cancelar assinatura */
        delete: operations["cancelSubscription"];
        options?: never;
        head?: never;
        /** Atualizar assinatura (parcial) */
        patch: operations["updateSubscription"];
        trace?: never;
    };
    "/subscriptions/{id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pausar assinatura */
        post: operations["pauseSubscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscriptions/{id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retomar assinatura */
        post: operations["resumeSubscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar endpoints de webhook */
        get: operations["listWebhookEndpoints"];
        put?: never;
        /** Criar endpoint de webhook */
        post: operations["createWebhookEndpoint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter endpoint de webhook */
        get: operations["getWebhookEndpoint"];
        /** Atualizar endpoint de webhook */
        put: operations["replaceWebhookEndpoint"];
        post?: never;
        /** Remover endpoint de webhook */
        delete: operations["deleteWebhookEndpoint"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar notificações */
        get: operations["listNotifications"];
        put?: never;
        /** Enviar notificação */
        post: operations["createNotification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter notificação */
        get: operations["getNotification"];
        /** Atualizar notificação (ex. reagendar) */
        put: operations["replaceNotification"];
        post?: never;
        /** Cancelar/Excluir notificação */
        delete: operations["deleteNotification"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        ProviderName: "STRIPE" | "MERCADOPAGO" | "ASAAS";
        Address: {
            line1: string;
            line2?: string | null;
            city: string;
            state: string;
            postal_code: string;
            /** @description ISO-3166-1 alpha-2, ex: BR */
            country: string;
        };
        ErrorResponse: {
            error?: {
                /** @enum {string} */
                code: "invalid_request" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "rate_limited" | "provider_error" | "temporary_unavailable";
                message: string;
                details?: {
                    path?: string;
                    rule?: string;
                }[];
                provider_context?: {
                    name?: components["schemas"]["ProviderName"];
                    status?: number;
                    provider_code?: string;
                };
                correlation_id?: string;
            };
        };
        Customer: {
            id: string;
            name: string;
            /** Format: email */
            email: string;
            tax_id?: string;
            phone?: string;
            address?: components["schemas"]["Address"];
            metadata?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at?: string;
        };
        CustomerList: {
            items?: components["schemas"]["Customer"][];
            has_more?: boolean;
            next_cursor?: string | null;
        };
        CreateCustomerRequest: {
            name: string;
            /** Format: email */
            email: string;
            tax_id?: string;
            phone?: string;
            address?: components["schemas"]["Address"];
            metadata?: {
                [key: string]: unknown;
            };
        };
        UpdateCustomerRequest: {
            name?: string;
            /** Format: email */
            email?: string;
            tax_id?: string;
            phone?: string;
            address?: components["schemas"]["Address"];
            metadata?: {
                [key: string]: unknown;
            };
        };
        /** @enum {string} */
        PaymentMethod: "CARD" | "BOLETO" | "PIX" | "CHECKOUT_LINK";
        /** @enum {string} */
        ChargeStatus: "PENDING" | "REQUIRES_ACTION" | "AUTHORIZED" | "PAID" | "FAILED" | "CANCELED" | "REFUNDED";
        InstallmentsRequest: {
            count: number;
            /** @enum {string} */
            interest_mode?: "NONE" | "BUYER" | "SELLER";
            /** @description Ex. 1.99 = 1,99% a.m. */
            interest_rate_pct?: number;
        };
        BoletoOptions: {
            /** Format: date */
            due_date?: string;
            instructions?: string;
            fine_pct?: number;
            interest_pct?: number;
        };
        PixOptions: {
            /** Format: date-time */
            expires_at?: string;
            payer?: {
                name?: string;
                tax_id?: string;
            };
        };
        ProviderPref: {
            prefer?: components["schemas"]["ProviderName"];
            data?: {
                [key: string]: unknown;
            };
        };
        CreateChargeRequest: {
            customer_id?: string;
            /** @description centavos */
            amount: number;
            /** @default BRL */
            currency: string;
            description?: string;
            payment_method: components["schemas"]["PaymentMethod"];
            installments?: components["schemas"]["InstallmentsRequest"];
            boleto?: components["schemas"]["BoletoOptions"];
            pix?: components["schemas"]["PixOptions"];
            /**
             * @description Somente cartão: authorize/capture
             * @default true
             */
            capture: boolean;
            return_url?: string;
            cancel_url?: string;
            items?: {
                name: string;
                quantity: number;
                unit_amount: number;
            }[];
            provider?: components["schemas"]["ProviderPref"];
            metadata?: {
                [key: string]: unknown;
            };
        };
        PaymentInstructions: {
            checkout_url?: string | null;
            qr_code_base64?: string | null;
            qr_code_text?: string | null;
            barcode?: string | null;
            /** Format: date-time */
            expires_at?: string | null;
        };
        ProviderContext: {
            name?: components["schemas"]["ProviderName"];
            /** @description ID da cobrança no provedor */
            id?: string;
            checkout_session_id?: string | null;
        };
        Charge: {
            id: string;
            status: components["schemas"]["ChargeStatus"];
            amount: number;
            currency: string;
            customer_id?: string | null;
            payment_method: components["schemas"]["PaymentMethod"];
            description?: string | null;
            installments?: {
                count?: number;
                effective_interest_rate_pct?: number;
                total_amount?: number;
            };
            payment_instructions?: components["schemas"]["PaymentInstructions"];
            provider_context?: components["schemas"]["ProviderContext"];
            metadata?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at?: string;
        };
        ChargeList: {
            items?: components["schemas"]["Charge"][];
            has_more?: boolean;
            next_cursor?: string | null;
            total?: number;
        };
        Refund: {
            id: string;
            charge_id: string;
            /** @enum {string} */
            status: "PENDING" | "SUCCEEDED" | "FAILED";
            amount: number;
            currency: string;
            reason?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        /** @enum {string} */
        SubscriptionStatus: "ACTIVE" | "PAUSED" | "CANCELED";
        CreateSubscriptionRequest: {
            customer_id: string;
            /** @description centavos */
            amount?: number;
            /** @default BRL */
            currency: string;
            /** @enum {string} */
            interval: "day" | "week" | "month" | "year";
            /** @default 1 */
            interval_count: number;
            /** @default 0 */
            trial_days: number;
            description?: string;
            provider?: components["schemas"]["ProviderPref"];
            metadata?: {
                [key: string]: unknown;
            };
        };
        UpdateSubscriptionRequest: {
            status?: components["schemas"]["SubscriptionStatus"];
            trial_days?: number;
            metadata?: {
                [key: string]: unknown;
            };
        };
        Subscription: {
            id: string;
            customer_id: string;
            status: components["schemas"]["SubscriptionStatus"];
            amount?: number | null;
            currency?: string;
            /** @enum {string} */
            interval: "day" | "week" | "month" | "year";
            interval_count: number;
            /** Format: date-time */
            current_period_end?: string | null;
            provider_context?: components["schemas"]["ProviderContext"];
            metadata?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at?: string;
        };
        SubscriptionList: {
            items?: components["schemas"]["Subscription"][];
        };
        WebhookEndpoint: {
            id?: string;
            url?: string;
            secret?: string;
            enabled_events?: ("charge.created" | "charge.updated" | "charge.paid" | "charge.refunded" | "charge.canceled" | "subscription.created" | "subscription.updated" | "subscription.canceled" | "customer.created" | "customer.updated")[];
            /** Format: date-time */
            created_at?: string;
        };
        CreateWebhookEndpointRequest: {
            url: string;
            enabled_events: ("charge.created" | "charge.updated" | "charge.paid" | "charge.refunded" | "charge.canceled" | "subscription.created" | "subscription.updated" | "subscription.canceled" | "customer.created" | "customer.updated")[];
        };
        UpdateWebhookEndpointRequest: {
            url?: string;
            enabled_events?: string[];
        };
        WebhookEndpointList: {
            items?: components["schemas"]["WebhookEndpoint"][];
        };
        /** @enum {string} */
        NotificationChannel: "EMAIL" | "SMS" | "WHATSAPP" | "PUSH";
        /** @enum {string} */
        NotificationStatus: "QUEUED" | "SENT" | "FAILED" | "CANCELED";
        CreateNotificationRequest: {
            customer_id: string;
            channel: components["schemas"]["NotificationChannel"];
            subject?: string;
            message: string;
            /** Format: date-time */
            send_at?: string | null;
            metadata?: {
                [key: string]: unknown;
            };
        };
        UpdateNotificationRequest: {
            subject?: string;
            message?: string;
            /** Format: date-time */
            send_at?: string | null;
            status?: components["schemas"]["NotificationStatus"];
            metadata?: {
                [key: string]: unknown;
            };
        };
        Notification: {
            id?: string;
            customer_id?: string;
            channel?: components["schemas"]["NotificationChannel"];
            subject?: string | null;
            message?: string;
            status?: components["schemas"]["NotificationStatus"];
            /** Format: date-time */
            send_at?: string | null;
            /** Format: date-time */
            delivered_at?: string | null;
            metadata?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        NotificationList: {
            items?: components["schemas"]["Notification"][];
        };
    };
    responses: {
        /** @description Requisição inválida */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Recurso não encontrado */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Conflito de estado */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listCustomers: {
        parameters: {
            query?: {
                /** @description Busca textual por nome/email/documento */
                q?: string;
                limit?: number;
                starting_after?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista paginada de clientes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerList"];
                };
            };
        };
    };
    createCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCustomerRequest"];
            };
        };
        responses: {
            /** @description Cliente criado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cliente */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    replaceCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCustomerRequest"];
            };
        };
        responses: {
            /** @description Atualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removido */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCustomerRequest"];
            };
        };
        responses: {
            /** @description Atualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listCharges: {
        parameters: {
            query?: {
                status?: components["schemas"]["ChargeStatus"];
                method?: components["schemas"]["PaymentMethod"];
                customer_id?: string;
                limit?: number;
                starting_after?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista paginada de cobranças */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChargeList"];
                };
            };
        };
    };
    createCharge: {
        parameters: {
            query?: never;
            header: {
                /** @description Chave idempotente para evitar duplicidades */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateChargeRequest"];
            };
        };
        responses: {
            /** @description Cobrança criada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Charge"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
        };
    };
    getCharge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cobrança */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Charge"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    cancelCharge: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancelada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Charge"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    updateCharge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    description?: string;
                    metadata?: {
                        [key: string]: unknown;
                    };
                };
            };
        };
        responses: {
            /** @description Atualizada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Charge"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    captureCharge: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description Valor em centavos (opcional para captura parcial) */
                    amount_to_capture?: number;
                };
            };
        };
        responses: {
            /** @description Capturada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Charge"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    refundCharge: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Centavos. Omitir para reembolso total. */
                    amount?: number;
                    reason?: string;
                    metadata?: {
                        [key: string]: unknown;
                    };
                };
            };
        };
        responses: {
            /** @description Reembolso criado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refund"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listSubscriptions: {
        parameters: {
            query?: {
                customer_id?: string;
                status?: "ACTIVE" | "PAUSED" | "CANCELED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de assinaturas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionList"];
                };
            };
        };
    };
    createSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSubscriptionRequest"];
            };
        };
        responses: {
            /** @description Assinatura criada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subscription"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Assinatura */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subscription"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    cancelSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancelada */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSubscriptionRequest"];
            };
        };
        responses: {
            /** @description Atualizada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subscription"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    pauseSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pausada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subscription"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    resumeSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ativada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Subscription"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listWebhookEndpoints: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de endpoints */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookEndpointList"];
                };
            };
        };
    };
    createWebhookEndpoint: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWebhookEndpointRequest"];
            };
        };
        responses: {
            /** @description Endpoint criado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookEndpoint"];
                };
            };
        };
    };
    getWebhookEndpoint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Endpoint */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookEndpoint"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    replaceWebhookEndpoint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateWebhookEndpointRequest"];
            };
        };
        responses: {
            /** @description Atualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookEndpoint"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteWebhookEndpoint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removido */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    listNotifications: {
        parameters: {
            query?: {
                customer_id?: string;
                status?: "QUEUED" | "SENT" | "FAILED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de notificações */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationList"];
                };
            };
        };
    };
    createNotification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateNotificationRequest"];
            };
        };
        responses: {
            /** @description Notificação criada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"];
                };
            };
        };
    };
    getNotification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Notificação */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    replaceNotification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNotificationRequest"];
            };
        };
        responses: {
            /** @description Atualizada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteNotification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removida */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
}
